# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-26 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('skar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('admission_fee', models.IntegerField(blank=True, null=True)),
                ('tuitor_fee', models.IntegerField(blank=True, null=True)),
                ('more_detail', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skar.Student')),
                ('subject', models.ManyToManyField(blank=True, to='skar.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skar.Teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='uploads/%Y/%m/%d'),
        ),
    ]
