# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-02-03 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skar', '0002_auto_20200126_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcategory',
            name='slug',
            field=models.SlugField(default='hello', max_length=60, verbose_name='SEO friendly url, use only aplhabets and hyphen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Headline'),
        ),
    ]
