# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-02-12 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skar', '0009_auto_20200211_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Subject')),
                ('name', models.TextField(blank=True, verbose_name='Message')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
